/*DELETE PARA ALOJAMIENTOS*/
DELETE FROM `alojamientos` WHERE `FIRMA` = ?

/*SELECT PARA LA PAGINA ALOJAMIENTOS*/
SELECT A.`FIRMA`, A.`NOMBRE`, A.`DIRECCION`, A.`TELEFONO`, A.`EMAIL`, A.`WEB`, P.`PROVINCUA` AS `PROVINCIA`, M.`MUNICIPIO`, R.`CODIGO_POSTAL` AS `CODIGO POSTAL`, CONCAT(SUBSTRING(A.`DESCRIPCION`, 1, 50),'...') AS `DESCRIPCION`, CONCAT(SUBSTRING(A.`DESCRIPCION_EUSKERA`, 1, 50),'...') AS `DESCRIPCION EUSKERA`, A.`CAPACIDAD`, T.`TIPO`, Y.`TIPO_EUSKERA` AS `TIPO EUSKERA`, K.`CATEGORIA`, A.`COORDENADAS`, A.`CALIDAD_ASEGURADA` AS `CALIDAD ASEGURADA`, A.`TIENDA`, A.`GASTRONOMICO`, A.`CLUB`, A.`RESTAURANTE`, A.`AUTOCARAVANA`, A.`SURFING` FROM `ALOJAMIENTOS` A, `RELACION_CP_MUNICIPIOS_PROVINCIAS` R, `MUNICIPIOS` M, `PROVINCIAS` P, `CATEGORIAS` K, `TIPOS` T, `TIPOS_EUSKERA` Y  WHERE A.`CODIGO_TIPOS` = T.`CODIGO` AND A.`CODIGO_TIPOS_EUSKERA` = Y.`CODIGO` AND A.`CODIGO_CATEGORIAS` = K.`CODIGO` AND A.`ID_RELACIONES` = R.`ID` AND R.`CODIGO_PROVINCIA` = P.`CODIGO` AND R.`INDICE_MUNICIPIO` = M.`INDICE` ORDER BY A.`NOMBRE`

/*SELECT DE LA PAGINA VER SELECCION*/
SELECT A.`FIRMA`, A.`NOMBRE`, A.`DIRECCION`, A.`TELEFONO`, A.`EMAIL`, A.`WEB`, P.`PROVINCUA` AS `PROVINCIA`, M.`MUNICIPIO`, R.`CODIGO_POSTAL` AS `CODIGO POSTAL`, A.`DESCRIPCION` AS `DESCRIPCION`, A.`DESCRIPCION_EUSKERA` AS `DESCRIPCION EUSKERA`, A.`CAPACIDAD`, T.`TIPO`, Y.`TIPO_EUSKERA` AS `TIPO EUSKERA`, K.`CATEGORIA`, A.`COORDENADAS`, A.`CALIDAD_ASEGURADA` AS `CALIDAD ASEGURADA`, A.`TIENDA`, A.`GASTRONOMICO`, A.`CLUB`, A.`RESTAURANTE`, A.`AUTOCARAVANA`, A.`SURFING` FROM `ALOJAMIENTOS` A, `RELACION_CP_MUNICIPIOS_PROVINCIAS` R, `MUNICIPIOS` M, `PROVINCIAS` P, `CATEGORIAS` K, `TIPOS` T, `TIPOS_EUSKERA` Y  WHERE A.`FIRMA` = @param AND A.`CODIGO_TIPOS` = T.`CODIGO` AND A.`CODIGO_TIPOS_EUSKERA` = Y.`CODIGO` AND A.`CODIGO_CATEGORIAS` = K.`CODIGO` AND A.`ID_RELACIONES` = R.`ID` AND R.`CODIGO_PROVINCIA` = P.`CODIGO` AND R.`INDICE_MUNICIPIO` = M.`INDICE` ORDER BY A.`NOMBRE`

/*SELECT DE LAS CATEGORIAS*/
SELECT `CATEGORIA` FROM `CATEGORIAS`

/*SELECT DE LOS TIPOS*/
SELECT `TIPO` FROM `TIPOS`

/*SELECT DE LOS TIPOS EUSKERA*/
SELECT `TIPO_EUSKERA` FROM `TIPOS_EUSKERA`

/*SELECT DE LAS PROVINCIAS*/
SELECT `PROVINCUA` FROM `PROVINCIAS`

/*SELECT DE LOS MUNICIPIOS DEPENDIENDO DE LA PROVINCIA*/
SELECT `MUNICIPIO` FROM `MUNICIPIOS` WHERE `INDICE` IN (SELECT `INDICE_MUNICIPIO` FROM `RELACION_CP_MUNICIPIOS_PROVINCIAS` WHERE `CODIGO_PROVINCIA` = '@param')

/*SELECT DEL INDICE DE MUNICIPIOS USANDO EL MUNICIPIO*/
SELECT `INDICE` FROM `MUNICIPIOS` WHERE `MUNICIPIO` = @param

/*SELECT DE LOS CODIGOS_POSTALES*/
SELECT * FROM `CODIGOS_POSTALES` WHERE `CODIGO_POSTAL` IN (SELECT R.`CODIGO_POSTAL` FROM `RELACION_CP_MUNICIPIOS_PROVINCIAS` R WHERE `INDICE_MUNICIPIO` IN (@param)) ORDER BY `CODIGO_POSTAL` ASC

/*SELECT DEL CODIGO DEL LOS TIPOS USANDO COMO CONDICION EL TIPO*/
SELECT `CODIGO` FROM `TIPOS` WHERE `TIPO` = @param

/*SELECT DEL ID DE RELACION USANDO CAMPOS ESPECIFICOS*/
SELECT R.`ID` FROM `RELACION_CP_MUNICIPIOS_PROVINCIAS` R WHERE R.`CODIGO_PROVINCIA` = (SELECT P.`CODIGO` FROM `PROVINCIAS` P WHERE P.`PROVINCUA` = @prov) AND R.`INDICE_MUNICIPIO` = (SELECT M.`INDICE` FROM `MUNICIPIOS` M WHERE M.`MUNICIPIO` = @muni) AND R.`CODIGO_POSTAL` = @codPos

/*SELECT DEL CODIGO DE CATEGORIA USANDO LA CATEGORIA*/
SELECT `CODIGO` FROM `CATEGORIAS` WHERE `CATEGORIA` = @param

/*UPDATE DE UN ALOJAMIENTO*/
UPDATE `ALOJAMIENTOS` SET `FIRMA` = @param0, `NOMBRE` = @param1, `DESCRIPCION_ABREVIADA` = @param2, `DESCRIPCION_ABREVIADA_EUSKERA` = @param3, `DESCRIPCION` = @param4, `DESCRIPCION_EUSKERA` = @param5, `TELEFONO` = @param6, `DIRECCION` = @param7, `CALIDAD_ASEGURADA` = @param8, `EMAIL` = @param9, `WEB` = @param10, `CLUB` = @param11, `RESTAURANTE` = @param12, `AUTOCARAVANA` = @param13, `TIENDA` = @param14, `CAPACIDAD` = @param15, `GASTRONOMICO` = @param16, `SURFING` = @param17, `COORDENADAS` = @param18, `CODIGO_TIPOS` = @param19, `CODIGO_TIPOS_EUSKERA` = @param20, `CODIGO_CATEGORIAS` = @param21, `ID_RELACIONES` = @param22 WHERE `ALOJAMIENTOS`.`FIRMA` = @param23

/*INSERT DE UN REGISTRO*/
INSERT INTO `alojamientos` (`FIRMA`, `NOMBRE`, `DESCRIPCION_ABREVIADA`, `DESCRIPCION_ABREVIADA_EUSKERA`, `DESCRIPCION`, `DESCRIPCION_EUSKERA`, `TELEFONO`, `DIRECCION`, `CALIDAD_ASEGURADA`, `EMAIL`, `WEB`, `CLUB`, `RESTAURANTE`, `AUTOCARAVANA`, `TIENDA`, `CAPACIDAD`, `GASTRONOMICO`, `SURFING`, `COORDENADAS`, `CODIGO_TIPOS`, `CODIGO_TIPOS_EUSKERA`, `CODIGO_CATEGORIAS`, `ID_RELACIONES`) VALUES ('AAAAAAAA', 'AAAAAAAAAAAAAA', 'AAAAAAAAAAAAAA', 'AAAAAAAAAAAAA', 'AAAAAAAAAAAAA', 'AAAAAAAAAAAAA', 'AAAAAAA', 'AAAAAAAAAAAA', '1', 'AAAAAAAAAA', 'AAAAAAAAAAAAAAA', '1', '1', '1', '1', '12', '1', '1', 'AAAAAAAAAAAAAAAAAAAAAAA', '2', '2', '2', '103');

/*INSERT PREPARADA DE ALOJAMIENTO*/
INSERT INTO `ALOJAMIENTOS` (`FIRMA`, `NOMBRE`, `DESCRIPCION_ABREVIADA`, `DESCRIPCION_ABREVIADA_EUSKERA`, `DESCRIPCION`, `DESCRIPCION_EUSKERA`, `TELEFONO`, `DIRECCION`, `CALIDAD_ASEGURADA`, `EMAIL`, `WEB`, `CLUB`, `RESTAURANTE`, `AUTOCARAVANA`, `TIENDA`, `CAPACIDAD`, `GASTRONOMICO`, `SURFING`, `COORDENADAS`, `CODIGO_TIPOS`, `CODIGO_TIPOS_EUSKERA`, `CODIGO_CATEGORIAS`, `ID_RELACIONES`) VALUES (@firma, @nombre, @desc_a, @desc_ae, @desc, @desce, @tlf, @dire, @cal, @email, @web, @club, @res, @auto, @tie, @capa, @gas, @surf, @coor, @tip, @tipe, @cate, @rela);